const data = {
  product: [
    {
      name: 'Free Shirt',
      slug: 'Free Shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      discription: 'A papular shirt',
    },
    {
      name: 'slim Shirt',
      slug: 'slim Shirt',
      image: '/images/shirt2.jpg',
      price: 40,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      discription: 'A papular shirt',
    },
    {
      name: 'glof Shirt',
      slug: 'golf Shirt',
      image: '/images/shirt3.jpg',
      price: 50,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      discription: 'A papular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'Fit Shirt',
      image: '/images/pants1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      discription: 'A papular shirt',
    },
    {
      name: 'lose Shirt',
      slug: 'lose Shirt',
      image: '/images/pants2.jpg',
      price: 80,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      discription: 'A papular shirt',
    },
    {
      name: 'hot Shirt',
      slug: 'hot Shirt',
      image: '/images/pants3.jpg',
      price: 90,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      discription: 'A papular shirt',
    },
  ],
};
export default data;
